# Keyword Classification

This notebook shows the process of the keyword classifcation used within the study

In [ ]:
import pandas as pd
import multiprocessing as mp
import numpy as np
import regex as re

import nltk
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.util import ngrams

from collections import Counter

nltk.download('stopwords')
nltk.download('punkt')

stopwords = set(stopwords.words('english'))

pd.set_option('display.max_rows', 50)
pd.set_option('display.max_colwidth', None)

df = pd.read_parquet("/Users/emma/Desktop/thesis/commentDataClean.parquet", engine="pyarrow")

In [69]:
df = df[~df['body'].isin(['removed', 'deleted'])]
dfs = df.sample(frac=.05)

In [70]:
dfs

,body,author,score,id,link_id,subreddit,author_flair_text,time
2357311,heres the thing his justices wont pick and choose like this. the same justices that are against abortion are also the same justices against same sex marriage.,PARK_THE_BUS,141,d9z5l6u,t3_5ct4ho,politics,None,2016-11-14 00:38:46
775937,i cant wait for you all to lose in the midterms. commies gonna commie and it is gonna be so good to watch you lose again.,mongoose-american,0,i8inz2a,t3_uotfr7,politics,None,2022-05-14 00:06:30
2209605,but he does represent the thinking of a large portion of the people in his district at least the ones who vote for him thats the sad part of the election of some of these tea party people. theres a huge disconnect in this country with a lot of rural people especially with a lot of backwards and religious thinking versus the urban and suburban people. thats really at the heart of this problem and these tea partiers being elected is just a big symptom.,freediverdude,4,c6otwrx,t3_11qs41,politics,None,2012-10-19 15:13:13
1262972,the reality is this story is probably going to get drowned out tomorrow when the supreme court announces its samesex marriage decision.,stilgar02,22,caqev15,t3_1h1lfy,politics,None,2013-06-26 05:37:04
1119667,its far more important to protect the public from hearing protest chants than to protect children from being rapedtraffickedetc.. s,cuisinart-hatrack,2446,iguiqrg,t3_w2zsxr,politics,None,2022-07-19 23:33:47
...,...,...,...,...,...,...,...,...
986949,not fee fees so much as human lives lost. the discussion is an important one even if its not threat or priority 1. but since you apparently prioritize lightning deaths as the statistical likelihood comparatively how shall we tackle that first,that_one_bastard,0,cxo8yij,t3_3vjaqm,politics,None,2015-12-05 18:39:45
1046007,no. he would leave it to the state. also if a doctor kills a fetus in the 7th month of pregnancy on purpose isnt he liable for murder,alragusa,1,c2fs8t7,t3_jwo4d,politics,None,2011-08-28 13:12:05
69518,i never claimed alive meant person though or maybe i miswrote something,calamityfriends,-6,igbov16,t3_vznddd,politics,None,2022-07-15 22:45:44
2503821,democrats are baby killers just like the phrase they yelled at vietnam veterans.,ShoutingMatch,8,g4hjebn,t3_ip3ake,conservative,,2020-09-08 22:12:39
118622,trump and pence is why you shouldnt stay home on election day just because your perfect person isnt on the ballot dont wait to be inspired to vote,dontKair,8,duyqa9v,t3_80wvex,politics,north carolina,2018-02-28 15:46:25

In [ ]:
pck = [
    "my choice", "bodily autonomy", "body autonomy", "womens rights", "reproductive rights",
    "abortion rights", "forced birth", "government control", "privacy", "unsafe abortions", 'christofacists', 
    "anti choice", "im prochoice", "fetus"
]

plk = [
    "abortion is murder", "unborn child", "killing babies", 'sanctity of life', "im prolife",
    "sanctity of life", "right to life", "protect the unborn", 
    "anti life", 'innocent', 'life begins at conception',
    "life liberty and the pursuit", "killing"
]


dfs['test'] = ""

def sent_score(text, pck, plk):
    pc_score = sum(1 for word in pck if word in text.lower())
    pl_score = sum(1 for word in plk if word in text.lower())

    if pc_score == 0 and pl_score == 0:
        return "None"
    if pc_score > pl_score:
        return "prochoice"
    if pc_score == pl_score:
        return "unclear"
    
    return "prolife"
    

dfs['test'] = dfs['body'].apply(lambda x: sent_score(x, pck, plk))

In [72]:
dfs['test'].value_counts()

test
None         113862
prochoice      2601
prolife        1658
unclear         115
Name: count, dtype: int64

In [75]:
pl = dfs[dfs['test'] == 'prolife']
pl[['body', 'test']].sample(10)

,body,test
1476536,thats not what i mean at all. the violation of the right to life was for everyone who used the system and had to wait so long. they introduced the private sector so if someone dies waiting they could say that if they wanted better treatment they could have gone to a private clinic so it was their choice to go to the public hospital. the problem is you will then be paying for both public and private care because you are still being taxed a crazy amount for public care even though you dont want to use it. you then loose the choice to go to the private clinic because you can no longer afford it because you tax rate is something like 30. right now only very wealthy people can afford private care in canada because they are the only ones who can afford paying 40 tax and paying for private treatment. so you end up with the middle class basically forced in to the public system and they end up getting the worse treatment.,prolife
875040,first with doctors you are simply denying care. with abortion you are actively scrambling the brains of someone else. thats why we have the triage system. it takes away all moral guesswork and is encoded into medical law. this is a far rarer situation but if conjoined twins came to the emergency room and one was dying youd separate them so the other can live. its exactly the same for a doomed embryo or fetus. if scrambling brains is wrong induce labor and withhold care. is that okay this is a part of the er job description. i dont think anyone should be forced to perform abortions if they dont want so take a different job that doesnt require it. now that doesnt mean you have to allow them to be on your property in the first place but once they are in that position they dont simply lose all their rights. the same people who fight to ban 100 of abortion support things like the castle doctrine. that doctrine got its start in america when a louisiana homeowner shot an innocent japanese exchange student who got the wrong house when trying to find a halloween party. the personal and property rights that affect men are sanctified by the rightwing. the gop is all for murder under just about every circumstance including executing the known innocent see cameron todd willingham and endless war. this sort of thing just makes you look like a crazy person it would make me look crazy if i didnt have hundreds of womankilling bills backing me up.,prolife
1161054,i just listened to the audio wooo bolding he is not saying they are similar. he is saying the choice about what to do with the baby is similar because the out of wedlock baby was unwanted and i assume the pregnancy itself shameful to him and that a choice had to be made by his daughter maybe whether to abort it or not. he really does not answer the question posed. how do you explain a no exceptions policy to a daughter or granddaughter that was raped and is now pregnant that they need to keep the baby against their will paraphrase for clarity he draws his analogy then just says im prolife period. you guys are looking for ill intent here and i dont think there is any. i agree this guys views on abortion are incorrect but i dont see where his comments make him a bad person deserving of scorn.,prolife
1838760,a bill that could allow the death penalty for women who receive abortions emerged as a pivotal issue in a state legislative race in texas. the legislation which was filed last year by state representative bryan slaton would allow women who receive an abortion to be charged with assault or homicide which carries the states death sentence. the battle over how republicans should handle the issue of abortion has become central in one gop primary in texas 91st congressional district which contains conservative suburbs north of fort worth. in the primary held earlier this month state representative stephanie klick was forced into a runoff with challenger david lowe. i support representative slatons bill lowe said. which was probably the strongest prolife bill to ever enter texas. the same law that protects stephanie you mei want those same laws to protect unborn children. klick however slammed the legislation saying the idea of sentencing women to death is absolutely abhorrent. instead she pointed to existing laws in texas that have already reduced the number of abortions in the state. abolishing abortion is important but i think we can do that without giving women the death penalty she said. lowe defended his support of the legislation saying it has nothing to do with the death penalty and that he is not even a fan of it. do we all agree that abortion is murder absolutely. there should be consequences for it he said pointing out that some women in texas have traveled to other states including oklahoma for the procedure. the bill aims to make abortion a capital offense. it only includes exemptions for pregnancies that seriously threaten the life of the mother but not rape or incest. it also instructs the state attorney general to direct a state agency to enforce those laws regardless of any contrary federal statute regulation treaty order or court decision according to the texas tribune. oh. theyre both awful and a new low for texas.,prolife
2172480,shouldnt be an issue. killing a human for convinece should not be allowed. it destroys equality for all. death penalty is legally considered harsher than life in prison. killing an innocent child due to the regret of the mother for her own actions is not only unjust it sets a precedent for killing humans based on age being legally acceptable. if one argues that poor people should be allowed because the child wouldnt have as good opportunities then the same can be applied to elderly on fixed incomes after times of inflation. yeah because age is just a relative construct and not actually a marker of maturity. also one step further is that if we dont have equal right to life then anyone else can be excluded on the basis that the right to life does not exist when its not actually a right because it is denied to certain innocent individuals. one can still argue for the death penalty for people that have violated our code as one that has willingly negated their social contract... but an innocent child has not done such. they did not cause the situation. therefor in punishing them you open the door to deny anyone the right to life as in function you have ended it as a right. just because you call something a right does not make it one. protecting it does. you cant have both the right to life and the right to have abortions. they are in natural conflict with each other. you logically have to choose one. thats the core issue. should all be protected or should only those we identify as worthy be protected. usually historically the 2nd one has ended in the genocide of over 100 million of all ages in the last century alone. why keep going down that same road to fight for something that was first legalized to oppress minority population counts when the focus was to find a way to make sure there were less minority people in the future than if left unchecked that was the intent of planned parenthood as admitted by one of its founders. now as reported to congress and a matter if public record they sell baby parts. not a fake conspiracy... a real proven one. blm unless they havent been born yet and we can get them first or if they want a good economy to prosper in right way of the blue wave. sad.,prolife
560300,you sir are drunk on koolaid. do you have a factuallogical rebuttal or are you hoping to simply win by claiming my view is so crazy it need not be rebutted the fact of the matter is that the total costs of the war not to mention the indrects costs in property damage and the death of 620000 americans is a far bigger number than the market value at the time of all southern slaves. additionally a buyout would likely not have needed to be for full market value. an immediate emancipation combined with a partial compensation would probably have been sufficient to prevent secession. this is how the british handled it for example. further lincoln did attempt to negotiate a buyout. obviously he didnt go high enough in his price though. you make it sound like slave owners were innocent victims cuz well slavery was normal and legal at the time isnt that great america is this amazing country where conformity is a valid excuse for crimes against humanity and morality is trickling down like poo from self righteous crooks instead of originating from free enlightened minds. youre looking at the era of slavery through 2010colored glasses. if you were a white southerner at the time and you felt that slavery was wrong and wanted to act in a way that reflected that morality the best thing you could was to buy a slaves freedom and the second best thing you could do since most could not easily afford option 1 was to buy a slave and simply not treat them like a slave in other words you treat them with the same respect as whites but the slave does still have to work for you thats the arrangement that allowed you to financially justify purchasing the slave. every slave at that point in time was...a slave the property of someone else. so if you couldnt afford to buy ones freedom the best you could do other than illegally sneaking them across the border was to buy them and have as voluntary a relationship with them as is feasible under the financial circumstances of the purchase. every slave you didnt buy was inevitably being treated inhumanely by another owner so it was a matter of lesser evils. so maybe thats more of a tangent than i intended but my point is that youre speaking as if everyone in the southern states was pure evil. slaves were a builtin part of the economy they were sanctioned by the state and that meant anyone not employing slaves in industries like farming was not going to be able to trade competitively in the marketplace. given all these circumstances it is most certainly a wrong committed on the slave owners to suddenly invalidate a class of property that up until that point was so crucial to economic survival that if you were in an affected industry you couldnt afford not to own slaves and also given that some of the people who were most concerned about the way blacks were being treated and wanted to do something to better the situation were slave owners. these are not opposing ideas. theres no reason to deny the wrongness of revoking property rights just because you believe that owning slaves is morally wrong. the country made a legal promise to the states that slaves would be valid legal property. ignoring that promise is its own moral wrong and a terrible economic precedent to set. i agree that if a buyout was not possible going to war to free the slaves made sense as a matter of strict morality. but i also see the wrongs on the other side of the issue and a buyout would have addressed both problems simultaneously.,prolife
1384198,you genuinely believe that pro life views are based on oppressing women for what shits and giggles theres no other reason you can imagine that someone might find abortion to be immoral in and of itself is it really so shocking to you that there would be a significant percentage of the population opposed to killing unborn children i just want you to ask yourself if youre really being honest here.,prolife
2150691,i was listening to whatsherface from south dakota repeatedly dodging questions about this case and i was just stunned that they are so bad at making their own argument. look i dont even agree with you and i can spit out exactly what you say here its a terrible thing that happened to her but we cant fix that by doing another terrible thing and killing the innocent life that was created. two wrongs dont make a right. if you actually believe yourself thats what you say. but no stumble around trying not to commit to any particular position about the pregnant 10 year old except thats awful.,prolife
1871049,what species is it... im interested. like i said if an unborn child is such a burden on the mother that her life is threatened or will likely be lost then the killing is justifiable selfdefense. i know it will continue but that doesnt mean legalizing it is right in any sort of way. i oppose killing innocent humans all around when its legal and when its illegal.,prolife
1928419,you keep talking about the right to life. no where in all the rights we grant people does it say that anyone has the right to use someone elses body against their will to sustain their own life. so even if you grant a fetus every right that humans have it still does not have the right to ise a womans body without her giving permission. being aborted means you are prevented from using someone elses organs. if you die as a result thats sad but your body failed you. your right to life isnt infringed. its just not murder. if it was then every person who didnt donate to a transplant patient would be guilty of murder. on the flip side if you die as a result of being shot thats murder. the unlawful taking of a life. the only difference choosing to take that life abortion isnt choosing to take a life. its choosing to not donate your organs to a patient who needs a transplant.,prolife

**NLTK Counter**

In [33]:
dfs['test'].value_counts()

test
None         11410
prochoice      248
prolife        156
unclear         10
Name: count, dtype: int64

In [ ]:
stance_df = dfs[dfs['test'].isin(['prochoice', 'prolife'])]

def tokenize(text, n):

    text= re.sub(r'[^\w\s]', '', text.lower())
    words = text.split()
    words = [word for word in words if word not in stopwords]
    return list(ngrams(words, n))

In [92]:
pro_choice = Counter()
pro_life = Counter()

for _, row in stance_df.iterrows():
    words = tokenize(row['body'], 3)
    if row['test'] == 'prochoice':
        pro_choice.update(words)
    elif row['test'] == 'prolife':
        pro_life.update(words)

pc_grams = set([bg for bg, _ in pro_choice.most_common(20)])
pl_grams = set([bg for bg, _ in pro_life.most_common(20)])

print('unique pc:', pc_grams - pl_grams)
print('unique pl:', pl_grams - pc_grams)

unique pc: {('whole', 'womans', 'health'), ('media', 'domain', 'privacy'), ('submission', 'automatically', 'removed'), ('roe', 'vs', 'wade'), ('pro', 'forced', 'birth'), ('automatically', 'removed', 'comes'), ('v', 'wade', 'court'), ('concerns', 'well', 'concerns'), ('support', 'womens', 'rights'), ('womens', 'reproductive', 'rights'), ('rights', 'womens', 'rights'), ('domain', 'privacy', 'concerns'), ('roe', 'v', 'wade'), ('comes', 'social', 'media'), ('privacy', 'concerns', 'well'), ('abortion', 'womens', 'rights'), ('rights', 'bodily', 'autonomy'), ('social', 'media', 'domain'), ('removed', 'comes', 'social')}
unique pl: {('believe', 'life', 'begins'), ('homeless', 'people', 'die'), ('one', 'right', 'murder'), ('think', 'abortion', 'murder'), ('people', 'like', 'trying'), ('abortion', 'murder', 'would'), ('numbers', 'chapter', '5'), ('life', 'liberty', 'pursuit'), ('killing', 'unborn', 'child'), ('right', 'life', 'liberty'), ('body', 'without', 'consent'), ('sexually', 'active', 'women'), ('innocent', 'human', 'beings'), ('survive', 'outside', 'womb'), ('innocent', 'proven', 'guilty'), ('life', 'begins', 'conception'), ('killing', 'unborn', 'children'), ('liberty', 'pursuit', 'happiness'), ('human', 'cell', 'importance')}