**This notebook shows the apparent ratio of 'on topic' vs 'off topic' comments via keyword classifer**

In [9]:
import pandas as pd
import multiprocessing as mp
import numpy as np
import regex as re
import string
import swifter

/Users/emma/anaconda3/envs/macs30123/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [51]:
comments = pd.read_parquet('/Users/emma/Desktop/thesis/actual_folder/clean/total_comments.parquet')

In [53]:
comments['keyword_search_body'] = comments['body'].str.replace(f"[{string.punctuation}]", " ", regex=True).str.strip()

In [13]:
comments

,body,author,created_utc,score,id,parent_id,link_id,subreddit,author_flair_text,time,on_topic,keyword_search_body
898101,"see, i don't believe it is. i believe abort...",caufield88uk,1630476493,-7,hb5n5m9,t1_hb5ktu5,t3_pfnh03,politics,None,2021-09-01 06:08:13,,see i don t believe it is i believe abort...
1636952,unconstitutional. the constitution grants citi...,Lazy_Example4014,1657110390,2,if2e8j7,t3_vsgn1t,t3_vsgn1t,politics,None,2022-07-06 12:26:30,,unconstitutional the constitution grants citi...
1766805,"oh i consider both, but it is 100% the choice ...",mikepictor,1659051224,5,ii23w1o,t1_ii230fx,t3_waa3kq,politics,None,2022-07-28 23:33:44,,oh i consider both but it is 100 the choice ...
799244,"pro-pregnancy, and not even healthy pregnancie...",bone_druid,1588856772,4,fprl4pi,t3_gf3zpv,t3_gf3zpv,politics,None,2020-05-07 13:06:12,,pro pregnancy and not even healthy pregnancie...
2477208,biden says a lot of things...,LikelySoutherner,1656717438,0,ieiil3o,t3_vpdo65,t3_vpdo65,Conservative,None,2022-07-01 23:17:18,,biden says a lot of things
...,...,...,...,...,...,...,...,...,...,...,...,...
399962,then you were well under the time frame they'r...,amayespost,1481151118,1,dax1dih,t1_dax15b6,t3_5h2aqm,politics,None,2016-12-07 22:51:58,,then you were well under the time frame they r...
9779,where i live smoking is already banned in all ...,[deleted],1232809478,1,c078vp9,t1_c078r5f,t3_7ruq1,politics,None,2009-01-24 15:04:38,,where i live smoking is already banned in all ...
1886981,"""i don't care if he aborts baby eagles""",ShelSilverstain,1665102749,152,irclapm,t1_irb424h,t3_xxbgcq,politics,None,2022-10-07 00:32:29,,i don t care if he aborts baby eagles
2329984,should parents be obligated to donate organs t...,International-Cut598,1.693002406E9,1,jxr8ga4,t1_jxr873z,t3_1614iob,Conservative,clarence thomas,2023-08-25 22:26:46,,should parents be obligated to donate organs t...
1388970,"guarantee her stupid ""non-profit"" is funded by...",dd027503,1653063570,265,i9cgwhf,t1_i9bzc4x,t3_uttz81,politics,None,2022-05-20 16:19:30,,guarantee her stupid non profit is funded by...

In [54]:
keywords = [
    "autonomy", "rights", "reproductive", 'women', 'cell', 'cells'
    "birth", "government control", 'christofacists', 'pro', 'anti', 'choice', 'life', 
    'rape', 'court', 'planned', 'raped', 'gosnell', 'gillead',
    "antichoice", "prochoice", "abortion", 'abort', "unborn", 'life', "prolife",'antilife', 'innocent', 'babies', 'kill', 'killing',
    'roe', 'dobbs', 'pregnancy', 'parent', 'pregnant', 'fetus', 'baby', 'murder', 'doctor', 'constitution', 'mother', 'religion'
]


comments['on_topic'] = ""

def on_topic(text):

    
    return any(keyword in text for keyword in keywords)

comments['on_topic'] = comments['keyword_search_body'].swifter.apply(on_topic)

Pandas Apply: 100%|██████████| 2489890/2489890 [00:30<00:00, 81749.63it/s]

In [55]:
comments['on_topic'].value_counts()

on_topic
False    1321826
True     1168064
Name: count, dtype: int64

In [56]:
pd.set_option('display.max_colwidth', None)
comments[comments['on_topic'] == False].sample(20)

,body,author,created_utc,score,id,parent_id,link_id,subreddit,author_flair_text,time,on_topic,keyword_search_body
451857,we have it everywhere here in california!,i-am-sancho,1506046726,1,dnc68yq,t1_dnc64zq,t3_71nko1,politics,None,2017-09-22 02:18:46,False,we have it everywhere here in california
1125084,what did her daddy do to this lady. it must have been a horrible childhood to believe something like this. she needs to get mental health and victim support as soon as possible.,OPA73,1651213100,3,i6mvzp2,t3_ue2qpb,t3_ue2qpb,politics,None,2022-04-29 06:18:20,False,what did her daddy do to this lady it must have been a horrible childhood to believe something like this she needs to get mental health and victim support as soon as possible
1142266,"right, congress, not the president",nitrot150,1651550478,1,i74arwe,t1_i74aofz,t3_uh61gv,politics,washington,2022-05-03 04:01:18,False,right congress not the president
1202449,last week the republicans judged a case where they decided to ban recovery for emotional harm in discrimination suits. they'll be reviving separate but equal soon enough.,Zexapher,1651666742,257,i7a7f9t,t1_i7a624j,t3_ui3wzr,politics,america,2022-05-04 12:19:02,False,last week the republicans judged a case where they decided to ban recovery for emotional harm in discrimination suits they ll be reviving separate but equal soon enough
1983454,"fuck this journalist. love when they have information that would idk at the time be interesting for people to know, nah lemme hold out until i try and release this book. at least i can make money off this",waiter_checkplease,1679623228,1,jdft6ut,t3_11zv4tf,t3_11zv4tf,politics,None,2023-03-24 02:00:28,False,fuck this journalist love when they have information that would idk at the time be interesting for people to know nah lemme hold out until i try and release this book at least i can make money off this
1658450,"a *holy* vessel, i'll have you know!",brezhnervous,1657408941,1,ifj6b3h,t1_iezga6j,t3_vrzf2w,politics,None,2022-07-09 23:22:21,False,a holy vessel i ll have you know
938776,and when a unicorn gets caught with a tumblerina mistress we can hypothetically what if that as well,symalus,1630673254,-1,hbfv3i5,t1_hbfpm3c,t3_ph2llw,politics,None,2021-09-03 12:47:34,False,and when a unicorn gets caught with a tumblerina mistress we can hypothetically what if that as well
2110419,great effort. they make really hard someti.. all the time.,returnFutureVoid,1.699701874E9,2,k8rsdup,t1_k8r884q,t3_17sexlx,politics,None,2023-11-11 11:24:34,False,great effort they make really hard someti all the time
1527129,"i know, this is concerning",Environmental-Use-77,1656214808,1,idrlqfe,t3_vk4nxy,t3_vk4nxy,politics,None,2022-06-26 03:40:08,False,i know this is concerning
1436796,this is a literal nightmare. i can't explain...,Dsarg_92,1656080787,1,idk8j5i,t3_vjpmiz,t3_vjpmiz,politics,None,2022-06-24 14:26:27,False,this is a literal nightmare i can t explain
1460275,truth. this is appalling and disgusting.,JediSwaggins,1656089349,3,idkv1yw,t1_idkutwe,t3_vjpng8,politics,None,2022-06-24 16:49:09,False,truth this is appalling and disgusting
89641,you need to educate yourself about what ndaa actually is... then make an informed decision,stonedoubt,1325600200,4,c3dj0ee,t1_c3dgr56,t3_o0sa4,politics,None,2012-01-03 14:16:40,False,you need to educate yourself about what ndaa actually is then make an informed decision
2055090,"""i'm not personally for it, but laws shouldn't be created based on my own subjective beliefs"" is the most sensible thing i've heard from a politician all year.",nikstick22,1.688029331E9,3,jpyz2g2,t3_14lkjwd,t3_14lkjwd,politics,None,2023-06-29 09:02:11,False,i m not personally for it but laws shouldn t be created based on my own subjective beliefs is the most sensible thing i ve heard from a politician all year
1058582,zero chance.,pedalfanatic1985,1638595848,1,hn5w8pz,t1_hn48sil,t3_r7744j,politics,None,2021-12-04 05:30:48,False,zero chance
1528824,so they all lied? no surprise. we knew that at the time. only fools believed them.,Educational_Permit38,1656224758,8,ids10ey,t3_vkrq5r,t3_vkrq5r,politics,None,2022-06-26 06:25:58,False,so they all lied no surprise we knew that at the time only fools believed them
1281555,only if you follow this newfangled science stuff. im sure witchfinder alito could give you a few tips. he seems up to date on all the latest methods.,DaoFerret,1651968630,4,i7qmef4,t1_i7q5v0s,t3_ukl04j,politics,None,2022-05-08 00:10:30,False,only if you follow this newfangled science stuff im sure witchfinder alito could give you a few tips he seems up to date on all the latest methods
697463,boner.,chillum1987,1558526519,2,eof8a3a,t1_eoehpkm,t3_brfonq,politics,None,2019-05-22 12:01:59,False,boner
1828129,can't pharmacists decline to give out plan b on religious or moral grounds?,CaptainCAAAVEMAAAAAN,1662245641,7,imzi2xq,t3_x52db4,t3_x52db4,politics,None,2022-09-03 22:54:01,False,can t pharmacists decline to give out plan b on religious or moral grounds
1368446,monty python has a great song about it; every sperm is sacred.,mmitchener,1652485552,9,i8ilh4c,t3_up4baq,t3_up4baq,politics,None,2022-05-13 23:45:52,False,monty python has a great song about it every sperm is sacred
2243719,friendly reminder that the gop and all they stand for is vile. please remember to vote for all down ballot races as well in your state! local politics matter!,iheartpedestrians,1.727215425E9,22,lorfzf3,t3_1fol8mc,t3_1fol8mc,politics,None,2024-09-24 22:03:45,False,friendly reminder that the gop and all they stand for is vile please remember to vote for all down ballot races as well in your state local politics matter

In [61]:
on_topic = comments[comments['on_topic'] == True]

In [57]:
labeled = pd.read_csv('/Users/emma/Desktop/thesis/actual_folder/relabeled_data_clean.csv')

In [63]:
# Identify rows in 'labeled' that are NOT in 'new_data'
missing_data = labeled[~labeled['id'].isin(on_topic['id'])]

missing_data['my_label'].value_counts()

my_label
no stance    209
prochoice      7
prolife        3
unclear        1
Name: count, dtype: int64

In [68]:
data = labeled[labeled['id'].isin(on_topic['id'])]

data['my_label'].value_counts()

my_label
prochoice    472
prolife      406
no stance    371
unclear       23
Name: count, dtype: int64

In [70]:
data.to_csv('~/Desktop/test.csv', index=False)

In [69]:
data[data['my_label'] == 'no stance']

,body,author,created_utc,score,id,parent_id,link_id,subreddit,author_flair_text,time,my_label
7,the most guaranteed way to get rich is to help rich people protect their resources and acquire more.,selectrix,1.287341e+09,41,c12kabu,t1_c12k2w5,t3_dsdqs,politics,NaN,2010-10-17 18:48:15,no stance
9,"look. the point i am trying to make is that your conclusion that the parties are the same is simply not valid. though they may have similarities, and they do, they still have differences. that is why your argument is not sustainable. for instance, one party fought hard to end the denial of health insurance based on pre-existing conditions. the other was happy to allow that to continue. i could find the vote on health care reform but i am pretty sure you probably already know it. and because they voted differently there and differently on many other issues (civil rights, abortion, etc) they are different. no matter how many similarities you point out, as long as i am able to point out differences the parties remain different. it's the definition of the word. calling them the same just isn't valid. i am sure i will get a downvote without explanation but i don't know how to make my argument more clear. by calling the parties the same you are ignoring many of the great political battles of the last century. at the same time, however, i will not argue that they do not have similarities. the conclusion that they are the same, though, is just wrong. can you point out a peer-reviewed political scholar that actually makes the argument that the two parties are the same? i would be interested in reading their work. edited for clarity",aliveshecried,1.288980e+09,1,c14lbpo,t1_c14k456,t3_e1bj4,politics,NaN,2010-11-05 17:54:16,no stance
11,"i thought the same thing, but i figure she just fumbled some words in a very emotional and personal story. i found it highly doubtful she she doesn't know the difference (particularly since she had the procedure). but on her site, she mixes it up again in a different way. > the fetus slipped from my uterus into my vagina and could not survive. -- [link](link i'm sure the complication she's speaking of is the moving of the fetus from the uterus to the cervix. though i suppose once you start traveling down the cervix, you're on your way to the vagina.",krunk7,1.298068e+09,4,c1hdfe8,t1_c1hd2ch,t3_fo028,politics,NaN,2011-02-18 22:30:56,no stance
12,"or really, it shouldn't be ""pro-life"", but rather ""anti-abortion."" i find that a lot of pro-lifers are also pro-war, whiiich is basically another form of killing (for the sake of the argument, abortion will be considered a form of killing). which doesn't make sense to me. when i hear the term pro-life, i really think of hippies who are vegan, who are anti-any kind of ""killing"" murder--not *just* anti-abortion.",thesalemdit,1.298326e+09,2,c1hqfc1,t1_c1hoj02,t3_fpbaa,politics,NaN,2011-02-21 22:02:49,no stance
13,"american conservatives are not the same as real conservatives. republicans are not conservatives, they have just warped the semantic meaning of the word to mean 'reactionary'",[deleted],1.299369e+09,5,c1jhrm7,t1_c1jhelq,t3_fxzkb,politics,NaN,2011-03-05 23:50:53,no stance
...,...,...,...,...,...,...,...,...,...,...,...
1466,"wouldn't making the requirement for reporting increase the reports? kinda set a deadline? a statute of limitation for reporting rapes would increase the likelyhood of reporting, also would keep the testemonies fresh and less likely to be conjured up.",zwind,1.421964e+09,1,cnxmkph,t3_2taf04,t3_2taf04,Conservative,NaN,2015-01-22 21:53:33,no stance
1467,"it will fire up your college ""educated"" corporate hr laptop types, who might have otherwise lost energy now that trump is gone. expect lot's of ""in light of recent attacks on womens' rights..."" type of memos and zoom meetings in academic and corporate environments.",Wooden_Worldliness_8,1.651546e+09,3,i741dut,t1_i73pbux,t3_uh454k,Conservative,NaN,2022-05-03 02:43:13,no stance
1475,"i agree with you that birth control and abortions(im pro-choice as well) shouldnt be profit driven, but the us system sort of requires it due to how polarized the issue is here. most hospitals refuse to do it unless its absolutely necessary to save the life of the mother so they can stay out of the debate. knowing this a bunch of state legislatures are trying to close privately clinics by making it law that the doctors at private clinics need to having admitting privileges at a nearby hospital. well since the hospitals dont want to touch the issue, the doctors cant get those privileges and they are forced to shut down. our healthcare system is fucked up, and is an embarrassment compared with the rest of modern countries.",goldybear,1.545281e+09,2,ec5tjye,t1_ec5sxer,t3_a7428o,Conservative,###,2018-12-20 04:40:14,no stance
1476,"i don't know if warren quite understands the nature of the debate in question. frankly, i'm starting to doubt that she is capable of understanding it with such an asinine statement. the question of abortion isn't a question of if we can, or how difficult, or even how much danger does it risk the parent. the question is whether the mother's right to bodily autonomy supersedes another human's right to life. regardless as to what my answer to aforementioned question is, not addressing it only alienates those who understand the nature of the question.",Gretshus,1.565303e+09,1,ewdm7px,t3_cnkq10,t3_cnkq10,Conservative,don't tread on me,2019-08-08 22:25:02,no stance
1487,"i dont believe that life begins at conception, so no. a large percentage of miscarriages happen before the woman even knows she is pregnant.",liefelijk,1.606082e+09,2,gd9m4pj,t1_gd9lllw,t3_jywg7k,Conservative,NaN,2020-11-22 22:00:52,no stance

In [65]:
missing_data[missing_data['my_label'] == 'prolife']

,body,author,created_utc,score,id,parent_id,link_id,subreddit,author_flair_text,time,my_label
38,you know what's more effective than both? stop having sex so often. or pay for it yourself and don't expect me to pay for it for you.,[deleted],1.335425e+09,0,c4grtd7,t1_c4gf63t,t3_sqe1o,politics,NaN,2012-04-26 07:30:30,prolife
320,"see? now you are starting to get it. abstinence is the best form of contraceptive. if you don't want to have children, you don't have sexual intercourse. thank you bette midler, for bringing common sense to conversation.",ScroungerYT,1.630808e+09,-28,hbn2dly,t3_pi24vv,t3_pi24vv,politics,NaN,2021-09-05 02:05:31,prolife
703,between this and the gosnell trial evidence that should be enough to get it banned nation-wide.,TheDailyCosco,1.549761e+09,4,eg4k19l,t3_aox2qg,t3_aox2qg,Conservative,conservative,2019-02-10 01:05:38,prolife